version: '3.9'

services:
  nginx:
    image: nginx:1.25.3-alpine3.18
    volumes:
      - ./:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    #ports:
    #  - "${NGINX_PORT}:8000"
    profiles:
      - nginx

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    #ports:
    #  - "${PHP_FPM_PORT:?}:9000"
    profiles:
      - app

  mysql:
    image: 'mysql:8.4.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${DB_DATABASE:?}"
      MYSQL_USER: "${DB_USER:?}"
      MYSQL_PASSWORD: "${DB_PASSWORD:?}"
    #ports:
    #  - "${DB_PORT:?}:3306"
    volumes:
      - ./db:/var/lib/mysql
    profiles:
      - mysql
